### ISSUE TITLE
Nos campos lógicos

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mptrv/macrosvba#15]
```
Descrição detalhada:

Nos campos lógicos colocar sim ou não, hoje usa-se -1 e 01.

```

Original issue reported on code.google.com by `vania.ja...@gmail.com` on 8 Nov 2012 at 6:42

**Comment by mptrv** [comment]
Em alguns relatórios, já está assim. Em outros, isto será feito conforme requisições mais específicas.
