### ISSUE TITLE
Criar histórico de regime de trabalho

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mptrv/macrosvba#21]
```
Descrição detalhada:

Criar mecanismo para armazenar o histórico das alterações de regime de 
trabalho.
```

Original issue reported on code.google.com by `mpt...@yahoo.com.br` on 21 Nov 2012 at 8:47

**Comment by mptrv** [comment]
Não há necessidade, pois, dada a integração com o Sistema Acadêmico, já se possui tal histórico.
