### ISSUE TITLE
Pesquisa de salas como a de carga horária dos professores

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mptrv/macrosvba#42]
```
Descrição detalhada:

> Elaborar pesquisa de sala como a de carga horária dos professores. 
Inclusive, para geração da "carga horária" da sala.

```

Original issue reported on code.google.com by `mpt...@yahoo.com.br` on 15 Mar 2013 at 1:54

**Comment by mptrv** [comment]
Indiretamente, já tem-se algo neste sentido implementado. Talvez seja melhor complementado com o recurso de reserva de salas a se implementar.
