### ISSUE TITLE
Histórico de Alteração de data - inicial e final

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mptrv/macrosvba#47]
```

    Colocar no Sistema Horários histórico da alteração de Categoria do professor, Cursos e disciplinas. 
```

Original issue reported on code.google.com by `vania.ja...@gmail.com` on 24 Jul 2013 at 6:29

**Comment by mptrv** [comment]
Dada a integração com o Sistema Acadêmico, já há histórico para a Categoria. Para os cursos e disciplinas, há de ser implementado em próximas fases da integração. Por ora, há um "pseudo-histórico", por recuperação de "backups" do banco de dados.
