### ISSUE TITLE
Não permitir que a aula seja contemplada ao professor licenciado

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mptrv/macrosvba#48]
```

O Sistema de horários deve de alguma forma bloquear atribuição de aulas 
durante o período que determinado professor estiver de licença. 
```

Original issue reported on code.google.com by `vania.ja...@gmail.com` on 24 Jul 2013 at 6:32

**Comment by mptrv** [comment]
Por ora, não será implementado. A se verificar tal necessidade. Ver também o "issue" #56.
