### ISSUE TITLE
Professores sem atribuição de aula.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mptrv/macrosvba#56]
```
Descrição detalhada:

> Nos relatórios de violações das restrições de carga horária, relatar 
também os professores que não possuem atribuição de aula e encontram-se 
ativos, assim como aqueles que encontram-se desligados ou de licença e possuem 
atribuição de aula.

```

Original issue reported on code.google.com by `mpt...@yahoo.com.br` on 21 Mar 2014 at 7:13

**Comment by mptrv** [comment]
O relatório "Mín 6 h-a por Semana não Atendido" já informa quando o professor não possui atribuição de aula.

Quanto aos professores desligados, dada a integração com o Sistema Acadêmico, não devem ocorrer atribuições inválidas, pois só são considerados os professores ativos.

Quanto aos de licença, podem ter aula atribuída, por ora, pois a licença pode expirar até o início das aulas, enquanto que os lançamentos podem ocorrer antes de tal início.
